### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by kdchambers** [musi-musi/munleko#2]
I can confirm this project works fine on my system. The only (minor) issue I noted is that there probably isn't a frame-rate limiter as I got quite high CPU utilisation.

Zig 0.11.0-dev.811+8ff9284c4 with Linux + Sway (Wayland)

**Comment by musi-musi** [comment]
latest commit added a vsync toggle with (press f10) but high usage is caused by the world update thread
when there are no updates to process, the thread spins until something changes (like an observer moving, causing chunks to load and unload)

i have plans to add a condition variable so the thread sleeps when it has nothing to do but i have another bug to fix first (see #3 )
